
const actionTypes = {
    CURRENTUSER: 'CURRENTUSER',
    CURRENTUSERUID: 'CURRENTUSERUID',
    USERDATA: 'USERDATA',
    LOADER: 'LOADER',
    ALLUSERS: 'ALLUSERS',
    ALLMESSAGES: 'ALLMESSAGES',
    FLAG: 'FLAG',
    MYREQUEST: 'MYREQUEST',
    OTHERREQ: 'OTHERREQ',
    MODIFYREQ: 'MODIFYREQ',
    MYCONTACT: 'MYCONTACT',
    ADMINMSG: 'ADMINMSG',
    CATEGORIES: 'CATEGORIES'
}

export default actionTypes